version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: mysql_astro_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: astro_db
      MYSQL_USER: astrouser
      MYSQL_PASSWORD: astropassword
    ports:
      - '3306:3306'
